-- 1. Crear tabla de reportes
CREATE TABLE "public"."reportes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "asesor_id" text not null, -- Chat ID o username del asesor
    "cedula_contrato" text not null,
    "estado" text not null default 'pendiente'::text, -- pendiente, procesado, devuelto
    "mensaje_admin" text, -- Para devoluciones
    "imagen_admin_url" text, -- Imagen opcional de devolucion
    "monto_total_aprox" text -- Calculado opcional basandose en pagos_asociados
);
ALTER TABLE "public"."reportes" ADD CONSTRAINT "reportes_pkey" PRIMARY KEY ("id");

-- 2. Crear tabla de transferencias asociadas al reporte
CREATE TABLE "public"."pagos_asociados" (
    "id" bigint generated by default as identity not null,
    "reporte_id" bigint not null references "public"."reportes"("id") on delete cascade,
    "fecha_pago" date not null,
    "cedula_cuenta" text not null,
    "telefono_bancario" text,
    "imagen_url" text not null
);
ALTER TABLE "public"."pagos_asociados" ADD CONSTRAINT "pagos_asociados_pkey" PRIMARY KEY ("id");

-- 3. Habilitar Storage (Crear Bucket)
insert into storage.buckets (id, name, public) values ('comprobantes', 'comprobantes', true);

-- 4. Politicas Publicas Temporales (Demo Rapida, se recomienda asegurar luego de probar)
CREATE POLICY "Public Access" ON "public"."reportes" FOR ALL USING (true);
CREATE POLICY "Public Access" ON "public"."pagos_asociados" FOR ALL USING (true);

create policy "Public Storage Access"
on storage.objects for all
using ( bucket_id = 'comprobantes' );
