-- 1. Crear tabla de usuarios
CREATE TABLE "public"."usuarios" (
    "username" text not null primary key,
    "password" text not null, -- En producción esto debería estar hasheado
    "role" text not null default 'asesor'::text -- 'asesor' o 'admin'
);

-- Insertar usuarios de prueba
INSERT INTO "public"."usuarios" (username, password, role) VALUES 
('cesar_asesor', '123456', 'asesor'),
('admin_vnet', 'admin123', 'admin');

-- 2. Crear tabla de reportes
CREATE TABLE "public"."reportes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "asesor_id" text not null references "public"."usuarios"("username"), -- Relación con el usuario
    "cedula_contrato" text not null,
    "estado" text not null default 'pendiente'::text, -- pendiente, procesado, devuelto
    "mensaje_admin" text, 
    "imagen_admin_url" text, 
    "monto_total_aprox" text 
);
ALTER TABLE "public"."reportes" ADD CONSTRAINT "reportes_pkey" PRIMARY KEY ("id");

-- 3. Crear tabla de transferencias asociadas al reporte
CREATE TABLE "public"."pagos_asociados" (
    "id" bigint generated by default as identity not null,
    "reporte_id" bigint not null references "public"."reportes"("id") on delete cascade,
    "fecha_pago" date not null,
    "cedula_cuenta" text not null,
    "telefono_bancario" text,
    "imagen_url" text not null
);
ALTER TABLE "public"."pagos_asociados" ADD CONSTRAINT "pagos_asociados_pkey" PRIMARY KEY ("id");

-- 4. Habilitar Storage (Crear Bucket)
insert into storage.buckets (id, name, public) values ('comprobantes', 'comprobantes', true);

-- 5. Políticas Públicas Temporales (Demo Rápida, se recomienda asegurar luego de probar)
CREATE POLICY "Public Access" ON "public"."usuarios" FOR ALL USING (true);
CREATE POLICY "Public Access" ON "public"."reportes" FOR ALL USING (true);
CREATE POLICY "Public Access" ON "public"."pagos_asociados" FOR ALL USING (true);

create policy "Public Storage Access"
on storage.objects for all
using ( bucket_id = 'comprobantes' );
